### ISSUE TITLE
help request: apinto启动后，转发服务可以正常访问，但api服务无法使用

### ISSUE THREAD

**Issue by A11Might** [eolinker/apinto#169]
### Description

使用apinto dashboard时报错：
```
Get "http://10.15.97.110:32313/profession/router/drivers": read tcp 10.15.97.110:64900->10.15.97.110:32313: read: connection reset by peer
```
排查发现转发服务可以正常访问，但open api服务无法使用。var/log/apinto/error.log中有报错日志：
```
[2024-10-10 17:07:03] [ERRO] [worker-71]plg manager: fail to createFilters filter,error is finchina_gateway_manager@output:worker-data not exits
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x186b744]

goroutine 1 [running]:
github.com/eolinker/apinto/drivers/plugins/access-log.getList({0xc0008400b0, 0x1, 0x498e7d?})
	/apinto/apinto_test/apinto/drivers/plugins/access-log/driver.go:29 +0xc4
github.com/eolinker/apinto/drivers/plugins/access-log.Create({
0xc0002ce430, 0xd}, {0xc0004f2c98, 0x6}, 0x1dbf040?, 0xc0001200d0?)
	/apinto/apinto_test/apinto/drivers/plugins/access-log/driver.go:47 +0x3f

github.com/eolinker/apinto/drivers.(*Driver[...]).Create(0xc000251680, 
{0xc0002ce430?, 0xd}, 
{0xc0004f2c98, 
0x6}, 
{0x19823e0, 0xc000207998?}, 0x0
?)
	/apinto/apinto_test/apinto/drivers/generics.go
:
26 +0x95

github.com/eolinker/apinto/drivers/plugin-manager.(*PluginManager).createFilters(0xc0004ed960, 0xc0008273e0)
	/apinto/apinto_test/apinto/drivers/plugin-manager/manager.go:127 +
0x47c
github.com/eolinker/apinto/drivers/plugin-manager.(*PluginManager).createChain(0xc0004ed960, {0xc0000f1cc0, 0x10}, 0xc0008273e0)
	
/apinto/apinto_test/apinto/drivers/plugin-manager/manager.go:145 +0x31

github.com/eolinker/apinto/drivers/plugin-manager.(*PluginManager).CreateRequest(0x4102d0
?, {
0xc0000f1cc0?, 
0x18bd446?
}, 0xc0000061c0?
)
	/apinto/apinto_test/apinto/drivers/plugin-manager/manager.go:
71 +0x18

github.com/eolinker/apinto/drivers/router/http-router.(*HttpRouter).reset(0xc000e85f40, 0xc0006dc540, 0xc000827470)
	/apinto/apinto_test/apinto/drivers/router/http-router/router.go:84
 +0x3d3
github.com/eolinker/apinto/drivers/router/http-router.Create({0xc0000f1cc0, 
0x10}, 
{0xc0000f1cd6, 
0x9}, 
0xc0006dc540, 0xc000827470
)
	/apinto/apinto_test/apinto/drivers/router/http-router/driver.go
:42 +0xe7

github.com/eolinker/apinto/drivers.(*Driver[...]
).Create(0xc0006dc540
, {0xc0000f1cc0
?, 0x10}
, {0xc0000f1cd6
, 0x9}
, {0x19809a0
, 0xc0006dc540?
}
, 0xc000827470
?)
	
/apinto/apinto_test/apinto/drivers/generics.go:26
 +0x95

github.com/eolinker/eosc/process-admin/admin.(*imlAdminData).setWorker(0xc00098e2a0, 0xc000838000)
	/root/go/pkg/mod/github.com/eolinker/eosc@v0.17.4/process-admin/admin/operator.go:68
 +0x703
github.com/eolinker/eosc/process-admin/admin.NewImlAdminData(
0xc0006578c0, 
{0x2150660
, 0xc000659e80}
, {0x2158e38
, 0xc0007edc80}
, 0x0)
	/root/go/pkg/mod/github.com/eolinker/eosc@v0.17.4/process-admin/admin/admin-data.go:102
 +0xf25
github.com/eolinker/eosc/process-admin.NewProcessAdmin({0x2146fb0, 0x326c300}, 0xc000657830)
	/root/go/pkg/mod/github.com/eolinker/eosc@v0.17.4/process-admin/process.go:172 +0x7ff
github.com/eolinker/eosc/process-admin.Process()
	/root/go/pkg/mod/github.com/eolinker/eosc@v0.17.4/process-admin/process.go:64 +0x134
main.ProcessAdmin()
	/apinto/apinto_test/apinto/app/apinto/admin.go:11
 +0x9b
github.com/eolinker/eosc/process.Run()
	/root/go/pkg/mod/github.com/eolinker/eosc@v0.17.4/process/process.go:109
 +0x230
main.main()
	/apinto/apinto_test/apinto/app/apinto/main.go:37
 +0x17

```
不确定和这个有关系吗，但配置的access_log插件是可以正常写日志到文件中

### Environment

- APINTO version (0.18.0):
- Operating system (Linux apinto-6df688c8d-gf8gk 5.14.0-362.13.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 14:07:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux):

**Comment by A11Might** [comment]
把挂载的目录（/var/lib/apinto）清空后，可以了
